defaults:
  - _self_
  - base_config

save_path: output/${run.id}/${data.name}/
model_name: model

mode:
  optimizer: novograd
  learning_rate: 0.001
  s2pmt_scaling: 1.0
  s2si_scaling: 1.0

physics:
  pmt_s2:
    bin_sigma: 0.1
  
